---
title: "Regressionsdiagnostik mit R"
author:  "Dr. Uwe Remer"
subtitle: "Eine einfache Einführung"
date: 2023-01-09
affiliation: "Universität Stutgart, CSS-Lab"
---

> WORK IN PROGRESS!

# Regressionsdiagnostik mit R

Dies ist das Skript zur *Videoserie Regressionsdiagnostik mit R*, welche für die Stelle Quantitative Methoden der [FernUni Hagen](https://www.fernuni-hagen.de/) entstanden ist.

Diese Videoserie besteht aus sechs aufeinander aufbauenden Teilen:

-   Teil 1: Einführung in die Regressionsdiagnostik. \[ [Video (11 Min.)](https://video.fernuni-hagen.de/Play/2521) \]
-   Teil 2: Das Anscombe Quartett sowie Beispiele für Modellverstöße \[  [Video (10 Min.)](https://video.fernuni-hagen.de/Play/2675) \]
-   Teil 3: Modellspezifikation und Multikollinearität  \[ [Video (32 Min.)](https://video.fernuni-hagen.de/Play/2676) \]
-   Teil 4: Außreißer und einflussreiche Werte \[ [Video (28 Min.)](https://video.fernuni-hagen.de/Play/2674) \]
-   Teil 5: Normalverteilte Fehler und konstante Fehlervarianzen \[ [Video (18 Min.)](https://video.fernuni-hagen.de/Play/2768) \]
-   Teil 6: Nicht-korrelierte Fehler, Linearitätsannahme und Fazit  \[[Video (23 Min.)](https://video.fernuni-hagen.de/Play/2769) \]

Zu allen Videos gibt es auf dieser Seite den R Code sowie das Skript.


## Voraussetzungen



## Zielgruppe

BA oder MA Studierende aus Wirtschafts- und Sozialwissenschaften, Psychologie oder Digital Humanities, mit Vorkenntnissen in quantitativen Methoden (Grundlagen in R und in multivariater Statistik, z.B. OLS Regression).

## Literatur zum Einstieg
